### ISSUE TITLE
Error loading object

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#122]
## Current Behavior
Following object ID link leads to "Loading" popup that never completes.

## Expected Behavior
Show me da file!

## Possible Solution
Fix it.

## Steps to Reproduce
Login, create a container (default private EACL), upload a JPEG.

## Your Environment
* Version of the product used: 0.3.1

**Comment by mike-petrov** [comment]
`private` EACL does not allow to upload any files, I got an error: 

<img width="363" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/b8f5e284-1ab2-4006-983a-a4da5ff2bc25">

**Comment by roman-khimov** [comment]
But supposedly I've got a token for it, no?

**Comment by mike-petrov** [comment]
Now we don't have any token

**Comment by roman-khimov** [comment]
Related to #126.

**Comment by roman-khimov** [comment]
Likely it was "personal" one in terms of Panel.

**Comment by mike-petrov** [comment]
Now it's a `forbid everything` preset with  `GET - DENY - OTHERS` rule and it should be available with the bearer token, but I got an error: `could not receive object: header: status: code = 2048 message = access to object operation denied`. 

@roman-khimov can you check one more time your case
