### ISSUE TITLE
Uploading big files never finishes

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#125]
## Current Behavior
Spinning circle.

## Expected Behavior
Successful upload.

## Possible Solution
Fix it.

## Steps to Reproduce
Try pushing 175M object into some container.

## Your Environment
* Version of the product used: 0.3.1

**Comment by mike-petrov** [comment]
We got `413 (Payload Too Large)` error, because use `POST https://rest.t5.fs.neo.org/v1/objects` request with body contains our file in base64 format:
```
attributes: [],
containerId: "G7iMQ8ih866Nc7uTHzSGPdwH2Jn2Mi2bY2BENYjEPHiz",
fileName: "photo.jpeg",
payload: "/9j/4AAQSkZ..."
```

REST should support binary uploading

**Comment by roman-khimov** [comment]
1. There should be an error shown to the user.
2. We can extend the size allowed.
3. Binary upload is possible after https://github.com/nspcc-dev/neofs-rest-gw/issues/111. Is it sufficient for the panel?
