### ISSUE TITLE
Too many tokens to sign

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#126]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I have to click through 10 tokens in my wallet to create a container and upload an object.

## Describe the solution you'd like
Less tokens to sign. Maybe one for container and one for object management.

**Comment by mike-petrov** [comment]
As far as I remember, the signing of 6 tokens was done intentionally so that the user could identify all 6 type of transactions

**Comment by roman-khimov** [comment]
IIUC https://rest.fs.neo.org/v1/docs current `/auth` API allows to get arbitrary tokens requested from the frontend, so we can solve this here.
