### ISSUE TITLE
Get mainnet balance get an error for Aero web wallet

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/panel-fs-neo-org#133]
WC testInvoke function get: `{code: -32000, message: 'Network request failed'}`

**Comment by mike-petrov** [comment]
As for Neon wallet everything is ok, thats why it might be problem Aero web wallet

**Comment by mike-petrov** [comment]
@roman-khimov we can remove aero web wallet from main page or mark it: `testnet`

**Comment by roman-khimov** [comment]
So it works for testnet, but doesn't for mainnet? Really strange.

**Comment by mike-petrov** [comment]
After updating the outdated WC SDK (https://github.com/nspcc-dev/panel-fs-neo-org/pull/138), the problem still exists

**Comment by roman-khimov** [comment]
After looking at https://github.com/melanke/aero-beta I don't think we can recommend it for mainnet. It's worth submitting an issue there anyway.
