### ISSUE TITLE
Redesign deposit and withdraw blocks for UX

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/panel-fs-neo-org#141]
Deposit & Withdraw operation related to `NeoFS chain balance`, but not good UX for understanding it.

<img width="739" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/3db3e2d7-d63e-4932-a5ca-2fc82040158d">

 It might be deposit/withdraw icons in `NeoFS chain balance` block.

**Comment by mike-petrov** [comment]
This enhancement only for UI improvements

**Comment by roman-khimov** [comment]
I see, still I'm not sure how it can be improved.

**Comment by mike-petrov** [comment]
Something like this or similar, maybe with noticeable icons or other meaningful icons:

<img width="995" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/6f12060e-7522-43fe-99a2-d73511d867e5">

**Comment by roman-khimov** [comment]
How about something like this (spacing should be improved, but you can get the idea)?

![Notes_240229_232651 (1)](https://github.com/nspcc-dev/panel-fs-neo-org/assets/22092804/d4a619fc-0e9e-4481-b949-8ffee8778e9e)

No panes, no cryptic buttons, just two balances and ways to move tokes around. Mobile-friendly.

**Comment by roman-khimov** [comment]
The word "Account" can be omitted as well, it's useless.

**Comment by mike-petrov** [comment]
Looks good, but on PC there will be an empty space on the right side, and I think we'll be mostly for PC
