### ISSUE TITLE
Add support for OneGate wallet

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#145]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when we can't work with wallets supported by https://governance.neo.org/

## Describe the solution you'd like

Research OneGate and what's needed to support it.

**Comment by mike-petrov** [comment]
As for [OneGate](https://onegate.space/), there are only mobile application:

**IOS**
- no app connection function, but have Store with `N3 Governments` dapp, thats why I think dapp have a web socket with local API

<img width="200" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/e983869e-a018-4748-a56b-9b75ce88755e">
