### ISSUE TITLE
Wallet selector tries to open a popup

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#177]
## Current Behavior
<img width="425" alt="Screenshot_20240318_213804" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/22092804/7b3dc73b-5c97-4386-8df0-edb0e9ccc305">

## Expected Behavior
Wallet selector appearing.

## Possible Solution
We can display the selector itself immediately on the page instead of "built with", there is not much you can do without a wallet anyway. Then it shouldn't trigger popups, it worked somehow without them before.

**Comment by mike-petrov** [comment]
It appears when you click on connect wallet? I thought it appears when you open new tab with neon wallet connection.

**Comment by roman-khimov** [comment]
Neon, yes. The panel with wallet list is displayed fine.

**Comment by roman-khimov** [comment]
It worked somehow in 0.4.0.

**Comment by roman-khimov** [comment]
I've just tried and it's the same for governance.neo.org. Weird.

**Comment by roman-khimov** [comment]
OK, let's leave it as is for now.
