### ISSUE TITLE
Add a note about OneGate to the login page

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#190]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when people can't handle OneGate login.

## Describe the solution you'd like
It's special, we know it, so right above the OneGate button there should be some note like "OneGate connection works only if you open the page from OneGate itself" (maybe with some references).

**Comment by roman-khimov** [comment]
BTW, likely it's possible to detect OneGate automatically and not bother with login at all. However it should be known that it's supported even if you're not currently using it.

**Comment by mike-petrov** [comment]
We can detect OneGate automatically, but I think we should give you a choice of wallets when you log in.

We can make it only show up when the browser supports it, but the web version won't show the onegate logo. Is that a normal solution? 

As for competitors, they have a division: on the mobile version only onagate is shown and on the web version all other wallets are shown.

**Comment by roman-khimov** [comment]
Some toggling between "Connect" (auto-detected) and "Hey, we support it too" text (not detected) is OK.
