### ISSUE TITLE
Autodetect Neoline

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#196]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we can do some things better, but don't do it. From https://flamingo.finance/ it looks like Neoline can be autodetected/autoconnected.

## Describe the solution you'd like
Make it easier for people with automatic connection.

## Additional context
Related to #190.

**Comment by mike-petrov** [comment]
I still believe that the user should have the choice of which wallet to connect, at the same time he can see what we support. 

 As for the `flamingo`, I always see the wallet selection popup, but button changes:
 
<img width="300" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/633cd454-e023-4d81-a1c1-aa4edd5fe9f4">
<img width="300" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/58b19f09-88b8-46cf-a2a3-bbe11b43d5ee">

**Comment by roman-khimov** [comment]
OK, works like that too.
