### ISSUE TITLE
Add a note about container creation cost

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#197]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when users don't know what's the cost of their operation.

## Describe the solution you'd like
Containers cost some GAS, this should be noted on the creation page.

**Comment by roman-khimov** [comment]
It'd also be nice to auto-update NeoFS balance after this operation.

**Comment by mike-petrov** [comment]
Tell me what text to include, I don't know the exact cost

**Comment by roman-khimov** [comment]
Container cost is 0.0070000014 GAS for mainnet now.
