### ISSUE TITLE
Handle misconfigured wallet connections

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#212]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when people try using Panel for testnet. Some (?) wallets allow users to choose the network for connection (even though we request mainnet) and if someone chooses testnet there we have a mess in UI. "Mainnet" balance becomes testnet balance, but NeoFS balance/containers are all mainnet. It's very confusing for people.

## Describe the solution you'd like
Check the connected network and refuse to work with anything but mainnet.

**Comment by mike-petrov** [comment]
**All our wallets:**
- NeoLine
    - 🔴 mobile (mainnet) – no have inner browser, but we can listed in the inner app gallery (https://github.com/nspcc-dev/panel-fs-neo-org/issues/224)
    - 🟢 chrome extension (mainnet  / testnet)
- O3
    - 🔴 mobile (mainnet) – in inner browser, but neo dapp not supported
    - 🟢 desktop (mainnet)
- Neon
    - 🟢 mobile (mainnet / testnet) – via qr-code
    - 🟢 desktop (mainnet  / testnet)
- OneGate
    - 🟢 mobile (mainnet) – in inner browser
    
symbols for v0.5.2:
🔴 - not support
🟢 - supported
