### ISSUE TITLE
Check Neon 3 compatibility

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#218]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I don't know if we're compatible with the latest and greatest Neon.

## Describe the solution you'd like
Check how Neon 3 works and if we're compatible with it.

**Comment by mike-petrov** [comment]
blocked v0.11.0 release (https://github.com/nspcc-dev/neofs-rest-gw/pull/238)

**Comment by mike-petrov** [comment]
**tested**

everything is fine
