### ISSUE TITLE
Consider token lifetimes 

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/panel-fs-neo-org#23]
Now panel doesn't set lifetime for the tokens. Default lifetime is [100](https://github.com/nspcc-dev/neofs-rest-gw/blob/d99c248a467fb4bfedc08589619a9286536d3544/spec/rest.yaml#L87) epochs (100 hours for public networks). Panel by default should use shorter lifetimes, a day (24) or even a couple of hours (2-3).

**Comment by mike-petrov** [comment]
To set up a new lifetime there are `X-Bearer-Lifetime` parameter in `POST /auth` route:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/32885629/201076900-9b698c13-e1a9-4e9d-a0d7-1c11ea7408d9.png">

**Comment by KirillovDenis** [comment]
Do we want to include this task to [v0.2.0](https://github.com/nspcc-dev/panel-fs-neo-org/milestone/2) ?
@alexvanin

**Comment by mike-petrov** [comment]
Decided to choose 2 epochs lifetime for the tokens.

/cc @alexvanin
