### ISSUE TITLE
Withdraw GAS not working

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/panel-fs-neo-org#38]
Withdraw GAS from NeoFS get a error: `Error: Failed to get system fee. Error: Script execution failed. ExecutionEngine state = FAULT. An unhandled exception was thrown. out of max amount limit`

**Comment by alexvanin** [comment]
Aside of having correct withdraw quantity, we should set correct scope. Right now panel does not use correct scope. Should be fixed.
