### ISSUE TITLE
Updated object management view

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/panel-fs-neo-org#61]
I propose to put all the buttons in one panel above the main information about the object, like on the picture:

<img width="717" alt="Снимок экрана 2022-10-17 в 12 25 19" src="https://user-images.githubusercontent.com/32885629/196738936-5cd39e35-73e2-47e0-ad38-a46d6c3c07a5.png">

**Comment by mike-petrov** [comment]
@roman-khimov I think it makes sense to do it in the new design, what do you think? I mean to group all the control buttons into one object section to make it clearer. Now we have not clear UI:

<img width="930" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/75fc51ff-7cd5-4829-bb13-116127fa22e8">

**Comment by roman-khimov** [comment]
Can be an improvement.
