### ISSUE TITLE
Check Neon wallet with NeoFS Panel 

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/panel-fs-neo-org#74]

**Comment by mike-petrov** [comment]
For the previous version 2.12.3 Neon wallet does not support WalletConnect v2, an error occurs:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/32885629/200289843-11132e79-0fde-46d1-8d01-fb5817c5858e.png">

In this case, we can make a branch `neon-wallet` to support first version WC.

But after that I upgraded Neon wallet to v2.14.1 and everything is fine. I suggest to put in the README which version you need to use the panel with best experience.

**Comment by mike-petrov** [comment]
Also Neon wallet to v2.14.1 sometimes unstable and gets an error:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/32885629/200308023-4aa0f42d-2c41-4e2c-95ba-c4afded8049f.png">

This happens sometimes when sending a transaction for signature from the web panel. In this case, I propose to abandon Neon wallet in favor of Aero web wallet for now.

**Comment by alexvanin** [comment]
> This happens sometimes when sending a transaction for signature from the web panel. In this case, I propose to abandon Neon wallet in favor of Aero web wallet for now.

We can mention that during migration stage, Neon wallet is considered unstable, yada-yada.

**Comment by mike-petrov** [comment]
Neon Wallet also has a mobile version, but Testnet is not supported in the mobile version:

![photo_2022-11-08 10 17 16](https://user-images.githubusercontent.com/32885629/200499142-e0d96d3f-3596-41d6-bae5-9242a1c07506.jpeg)
