### ISSUE TITLE
Logout on closed websocket connection

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/panel-fs-neo-org#79]
Can we do logout when the websocket connection were closed or expired (last error on scrennshot)?
![image](https://user-images.githubusercontent.com/11478618/201051900-16e8442d-0b91-498b-a150-d71f0bf5a5b3.png)

**Comment by mike-petrov** [comment]
In case of using aero wallet, you can close the aero tab and web socket will close. After that you have popup about it:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/32885629/201716771-32fc4af0-5208-4084-86f7-d9e9f459ea4c.png">

But if you open the closed tab again, everything will be fine. Should we logout from the web panel?

**Comment by KirillovDenis** [comment]
My case was explicitly removal connection from aero wallet (not closing tab).
