### ISSUE TITLE
Add development targets to Makefile

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/panel-fs-neo-org#84]
It would be nice to have some targets in Makefile for development purpose. Currently there is only one way to start app - using `make start` that takes up to 1 minute. It's too much when you just want to update the environment variables. 

Ideally we need hot reload support. At least we should add a target to run the app in development mode.
For instance we can have something like this (probable add condition dependency on target `all`):
```
dev:
	docker run \
	-p $(PORT):3000 \
	-v `pwd`:/usr/src/app \
	-w /usr/src/app node:14-alpine \
	sh -c 'npm start'
```

/cc @alexvanin

**Comment by alexvanin** [comment]
Maybe we need to split docker and non-docker targets. Use `docker/` prefix for those.
